app.client.frontend: http://localhost:3001

spring:
  application:
    name: learnX
  messages:
    basename: i18n/messages

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:mysql://localhost:3316/learnx_db
    # username: root
    # password:
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database: mysql
  jackson:
    serialization:
      indent-output: true
  # Redis server connection settings
  data:
    redis:
      host: 127.0.0.1 # Host of the Redis server
      port: 6319 # Port of the Redis server for connection
      password: ""  # Password for connecting to the Redis server (default is empty)
      lettuce:
        pool: # Connection pool settings
          max-active: 10 # Maximum number of active connections in the pool (uses -1 for no limit)
          max-idle: 5 # Maximum number of idle connections in the pool
          min-idle: 5 # Minimum number of idle connections in the pool
#          max-wait: -1ms # Maximum wait time to get a connection from the pool (uses -1 for no limit)
      connect-timeout: 30000 # Connection timeout (in milliseconds)
  threads:
    virtual:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: utezauth@gmail.com
    password: gyiuqpfjxzhywaui
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 660554863773-c5na5d9dvnogok0i23ekgnpr15to3rvn.apps.googleusercontent.com
            client-secret: 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
            scope: openid,email,profile

app:
  jwtSecret: WJCHZdb4R1p+qpHJ9/bwVLaiBWxz1wFbUDiZvWpDNLvXROOzueEqj5o/6x2s2v71

resilience4j:
  ratelimiter:
    instances:
      default:
        limitForPeriod: 1000
        limitRefreshPeriod: 1s
        timeoutDuration: 0

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

server:
  port: 9191
